Repository 13IEZ/glamping_front, pull requests merged in 2021-08, with the labels that each got.

#197 front-feature #159 Created component ReviewForm and its fuctionality
  src/App.tsx
  src/pages/ProductDetail/ProductDetail.tsx
  src/pages/ProductDetail/components/ProductDetailTab/ProductDetailTab.tsx
  src/pages/ReviewForm/PreviewForm.scss
  src/pages/ReviewForm/ReviewForm.tsx
  src/pages/Store/Store.tsx
  src/pages/Store/components/StoreItem/StoreItem.tsx
  src/store/actions/reviewsAction.ts
  src/store/types/reviewsTypes.ts
Labels: enhancement, feature

#199 front-feature #188 Created page Locations
  src/App.tsx
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/pages/Location/Locations.scss
  src/pages/Locations/Locations.scss
  src/pages/Locations/Locations.tsx
  src/pages/LocationsMap/LocationsMap.scss
  src/pages/LocationsMap/LocationsMap.tsx
  src/pages/LocationsMap/components/GLMap/GLMap/GLMap.tsx
  src/pages/LocationsMap/components/SelectList/SelectList.scss
  src/pages/LocationsMap/components/SelectList/SelectList.tsx
  src/pages/Main/components/LocationMini/LocationMini.tsx
  src/pages/Main/components/LocationMini/components/LocationItem.scss
  src/pages/Main/components/LocationMini/components/LocationItem.tsx
  src/pages/Main/components/LocationMini/components/LocationMiniItem.tsx
  src/store/types/locationsTypes.ts
Labels: feature

#200 front-feature #175 add side filtration, change top filtration, change…
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/pages/Store/Store.tsx
  src/pages/Store/components/StoreMenu/StoreMenu.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
  src/store/actions/categoriesAction.ts
  src/store/actions/productsAction.ts
  src/store/reducers/categoriesReducer.ts
  src/store/types/categoriesTypes.ts
Labels: feature

#201 front-feature #188 Deleted excess state (pages) from global store
  src/pages/ProductDetail/components/ProductDetailTab/ProductDetailTab.tsx
  src/pages/Store/Store.tsx
  src/store/configureStore.ts
Labels: bug

#214 front-bug #207 On page Locations did transparent background-color
  src/pages/Locations/Locations.scss
Labels: bug

#218 front-enhancement #217 improve side filtering functionality
  src/pages/Store/Store.scss
  src/pages/Store/Store.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
  src/store/actions/categoriesAction.ts
  src/store/actions/productsAction.ts
  src/store/reducers/categoriesReducer.ts
  src/store/types/categoriesTypes.ts
Labels: enhancement

#219 front-feature #208 add front jenkins CI/CD settings
  package.json
  src/settings/config.ts
Labels: feature

#221 front-but #206 chenged css in locations-map
  src/pages/LocationsMap/LocationsMap.scss
  src/pages/LocationsMap/LocationsMap.tsx
Labels: bug

#224 Bug 223
  src/pages/Store/Store.scss
Labels: bug

#228 front-bug #227 made small changes in the store block
  src/assets/_mixins.scss
  src/components/UI/AppToolbar/AppToolBar.scss
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/pages/Main/components/AccommodationMini/components/AccommodationMiniItem.tsx
  src/pages/ProductDetail/components/ProductDetailTab/ProductDetailTab.scss
  src/pages/Store/Store.scss
  src/pages/Store/components/StoreSidebar/StoreSidebar.scss
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
Labels: bug

#235 front-bug-enhancement #230 adapt pagination for filtering
  src/pages/Store/Store.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
  src/store/actions/productsAction.ts
  src/store/reducers/productsReducer.ts
  src/store/types/productsTypes.ts
Labels: bug, enhancement

#242 front-enhancement #241 finalize footer
  src/components/UI/CustomFooter/CustomFooter.tsx
Labels: enhancement

#245 front-bug-enhancement #244 adapt product card for new product features
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductDetail.tsx
  src/pages/Store/Store.tsx
  src/store/types/productsTypes.ts
Labels: bug, enhancement

#243 front-feature #229 Created reservationReducer and page UserPersonalAr…
  src/App.tsx
  src/hooks/useAction.ts
  src/pages/UserPersonalArea/UserPersonalArea.scss
  src/pages/UserPersonalArea/UserPersonalArea.tsx
  src/pages/UserPersonalArea/components/InvestorSection/InvestorSection.scss
  src/pages/UserPersonalArea/components/InvestorSection/InvestorSection.tsx
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.scss
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.tsx
  src/store/actions/reservationsAction.ts
  src/store/configureStore.ts
  src/store/reducers/reservationsReducer.ts
  src/store/types/reservationsTypes.ts
  src/store/types/users.ts
Labels: feature

#247 front-enhancement #205 add browser address string copy paste function…
  src/App.tsx
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/pages/Main/components/StoreMini/StoreMini.tsx
  src/pages/Store/components/StoreItem/StoreItem.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
Labels: enhancement

#252 front-enhancement #251 refactoring store modify pagination
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/pages/Store/Store.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
  src/store/actions/productsAction.ts
  src/store/reducers/productsReducer.ts
  src/store/types/productsTypes.ts
Labels: enhancement

#254 front-bug # 253 Did block of tourist in userPersonalArea
  src/App.tsx
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.tsx
  src/store/actions/reviewsAction.ts
  src/store/reducers/reviewsReducer.ts
  src/store/types/reviewsTypes.ts
Labels: bug, enhancement

#257 front-feature #187 add pichlist at currentlocation
  src/pages/CurrentLocation/CurrentLocation.scss
  src/pages/CurrentLocation/CurrentLocation.tsx
  src/pages/CurrentLocation/components/СurrentLocationPich/СurrentLocationPich.scss
  src/pages/CurrentLocation/components/СurrentLocationPich/СurrentLocationPich.tsx
  src/store/actions/pichesAction.ts
  src/store/reducers/pichesReducer.ts
  src/store/types/pichesTypes.ts
Labels: feature

#259 Merge branch 'enhancement-181'
  src/components/UI/AppToolbar/AppToolBar.scss
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/components/UI/Carousel/CustomCarousel.scss
  src/components/UI/Carousel/CustomCarousel.tsx
  src/pages/LocationsMap/LocationsMap.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/AboutApp/AboutApp.tsx
  src/pages/Main/components/AccommodationMini/AccommodationMini.tsx
  src/pages/Main/components/LocationMini/LocationMini.tsx
Labels: enhancement

#272 front-feature #271 created functionallity of getting all user's produ…
  src/pages/UserPersonalArea/UserPersonalArea.tsx
  src/pages/UserPersonalArea/components/InvestorSection/InvestorSection.tsx
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.tsx
  src/store/actions/productsAction.ts
  src/store/reducers/productsReducer.ts
  src/store/types/productsTypes.ts
Labels: feature

#275 front-but #274 Filtered reservations
  src/pages/UserPersonalArea/UserPersonalArea.tsx
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.tsx
Labels: bug

#287 Created block with piches's reservations of land owner
  src/pages/UserPersonalArea/UserPersonalArea.tsx
  src/pages/UserPersonalArea/components/LandOwnerSection/LandOwnerSection.tsx
  src/pages/UserPersonalArea/components/TouristSection/TouristSection.tsx
  src/store/actions/reservationsAction.ts
  src/store/reducers/reservationsReducer.ts
  src/store/types/pichesTypes.ts
  src/store/types/reservationsTypes.ts
Labels: feature
