Repository 13IEZ/glamping_front, pull requests merged in 2021-09, with the labels that each got.

#289 Block about reservations of accommodations
  src/pages/UserPersonalArea/components/LandOwnerSection/LandOwnerSection.tsx
  src/store/actions/reservationsAction.ts
  src/store/reducers/reservationsReducer.ts
  src/store/types/accommodationsTypes.ts
  src/store/types/reservationsTypes.ts
Labels: feature

#294 front-bug #293 prescribed the logic for sending applications for the…
  src/hooks/useAction.ts
  src/pages/Pitches/PitchRentalForm.tsx
  src/pages/Pitches/components/PitchDetailDescription/PitchDetailDescription.tsx
  src/pages/Store/components/NewProduct/NewProduct.tsx
  src/store/actions/applicationsAction.ts
  src/store/configureStore.ts
  src/store/reducers/applicationsReducer.ts
  src/store/types/applicationsTypes.ts
Labels: bug

#297 Added fixes as requested by the customer
  src/components/UI/Carousel/CustomCarousel.scss
  src/components/UI/Carousel/CustomCarousel.tsx
  src/pages/Main/components/StoreMini/components/StoreMiniItem.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
Labels: enhancement

#299 front-feature #298 add accomodation sort and filterig
  src/App.tsx
  src/pages/Accommodations/Accommodations.tsx
  src/pages/Accommodations/components/AccommodationSidebar.tsx
  src/pages/CurrentLocation/components/СurrentLocationPich/СurrentLocationPich.tsx
  src/pages/Main/components/AccommodationMini/AccommodationMini.tsx
  src/pages/Main/components/AccommodationMini/components/AccommodationMiniItem.tsx
  src/store/actions/accommodationsAction.ts
  src/store/reducers/accommodationReducer.ts
  src/store/types/accommodationsTypes.ts
Labels: feature

#301 front-bug #300 change Accomodation.ts
  src/pages/Accommodations/Accommodations.tsx
Labels: bug

#303 changed styles
  src/components/UI/CustomFooter/CustomFooter.tsx
  src/pages/CurrentAccommodation/components/Calendar/Calendar.scss
  src/pages/CurrentAccommodation/components/Calendar/Calendar.tsx
  src/pages/LocationsMap/LocationsMap.scss
  src/pages/Main/components/AccommodationMini/AccommodationMini.scss
  src/pages/Main/components/LocationMini/LocationMini.scss
  src/pages/Main/components/StoreMini/StoreMini.scss
  src/pages/Pitches/PitchRentalForm.scss
Labels: bug

#308 front-bug #307 add accomodation list
  src/store/actions/accommodationsAction.ts
  src/store/reducers/accommodationReducer.ts
Labels: bug

#310 front-bug #309 add currentaccommodations in CurrentLocationAccommodat…
  src/pages/CurrentLocation/components/CurrentLocationAccommodation/CurrentLocationAccommodation.tsx
Labels: bug

#312 front-enhancement #311 delete free field in pich
  src/pages/CurrentLocation/CurrentLocation.tsx
  src/pages/CurrentLocation/components/СurrentLocationPich/СurrentLocationPich.tsx
Labels: enhancement

#316 changed styles
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/components/UI/AppToolbar/Menus/AnonymousMenu.scss
  src/components/UI/Carousel/CustomCarousel.scss
  src/pages/Accommodations/Accommodations.scss
  src/pages/Accommodations/Accommodations.tsx
  src/pages/Main/components/AboutApp/AboutApp.tsx
  src/pages/Main/components/LocationMini/LocationMini.scss
  src/pages/Main/components/StoreMini/StoreMini.scss
  src/pages/ProductDetail/components/ProductDetailTab/ProductDetailTab.tsx
  src/pages/Register/Register.scss
  src/pages/Register/Register.tsx
  src/pages/Store/components/StoreSidebar/StoreSidebar.scss
  src/pages/Store/components/StoreSidebar/StoreSidebar.tsx
Labels: bug

#320 front-bug #318 fixed bugs
  src/components/UI/AppToolbar/Menus/UserMenu.scss
  src/components/UI/Carousel/CustomCarousel.scss
  src/components/UI/Carousel/CustomCarousel.tsx
  src/pages/Register/Register.tsx
  src/pages/Store/components/NewProduct/NewProduct.tsx
Labels: bug

#328 front-bug #327 Made edits according to the ticket
  src/App.tsx
  src/components/UI/AppToolbar/AppToolBar.scss
  src/components/UI/AppToolbar/AppToolbar.tsx
  src/components/UI/Carousel/CustomCarousel.scss
  src/pages/Accommodations/components/AccommodationSidebar.tsx
  src/pages/NewLocation/NewLocation.tsx
  src/pages/Pay/Pay.tsx
  src/pages/ProductDetail/components/ProductDetailDescription/ProductDetailDescription.tsx
  src/pages/Store/components/NewProduct/NewProduct.tsx
  src/pages/UserPersonalArea/components/InvestorSection/InvestorSection.tsx
  src/pages/UserPersonalArea/components/LandOwnerSection/LandOwnerSection.tsx
Labels: bug

#334 front-enhancement #333 add padding in ProductDetail.scss
  src/pages/ProductDetail/ProductDetail.scss
Labels: enhancement

#336 fixed bug
  src/components/UI/Carousel/CustomCarousel.scss
  src/components/UI/Carousel/CustomCarousel.tsx
Labels: bug

#338 Added link in menu
  src/components/UI/AppToolbar/Menus/UserMenu.tsx
Labels: enhancement
